

FROM python:3.13.4-slim-bullseye

WORKDIR /app

# curl -X POST -d "message=hello" -H "Content-Type: application/json" http://host.docker.internal:8000/chat
RUN apt-get update && apt-get install -y libpq-dev gcc curl

RUN pip install uv

# Configure uv to use a specific venv path
# This prevents the venv from being hidden if /app is mounted as a volume
ENV UV_PROJECT_ENVIRONMENT=/opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Create virtual environment
RUN uv venv /opt/venv
COPY ./pyproject.toml ./uv.lock ./
RUN uv sync --frozen 
COPY ./backend/src .

# CMD ["python", "-m", "http.server", "8000"]

